#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Com.StartLineSoft.SincronizadorRedCoopcentral
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="sincronizadorRedCoopcentral")]
	public partial class EntidadesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertConvenio(Convenio instance);
    partial void UpdateConvenio(Convenio instance);
    partial void DeleteConvenio(Convenio instance);
    partial void InsertTransaccion(Transaccion instance);
    partial void UpdateTransaccion(Transaccion instance);
    partial void DeleteTransaccion(Transaccion instance);
    partial void InsertDatoTransaccion(DatoTransaccion instance);
    partial void UpdateDatoTransaccion(DatoTransaccion instance);
    partial void DeleteDatoTransaccion(DatoTransaccion instance);
    #endregion
		
		public EntidadesDataContext() : 
				base(global::Com.StartLineSoft.SincronizadorRedCoopcentral.Properties.Settings.Default.sincronizadorRedCoopcentralConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public EntidadesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EntidadesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EntidadesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EntidadesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Convenio> Convenios
		{
			get
			{
				return this.GetTable<Convenio>();
			}
		}
		
		public System.Data.Linq.Table<Transaccion> Transaccions
		{
			get
			{
				return this.GetTable<Transaccion>();
			}
		}
		
		public System.Data.Linq.Table<DatoTransaccion> DatoTransaccions
		{
			get
			{
				return this.GetTable<DatoTransaccion>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.fn_obtener_numero_transaccion", IsComposable=true)]
		public System.Nullable<int> fn_obtener_numero_transaccion([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id).ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.convenios")]
	public partial class Convenio : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _CodigoConvenio;
		
		private string _EntidadNombre;
		
		private string _EntidadSigla;
		
		private string _EntidadNit;
		
		private string _LlaveA;
		
		private string _LlaveB;
		
		private string _Uri;
		
		private bool _Activo;
		
		private System.Nullable<System.DateTime> _CreatedAt;
		
		private System.Nullable<System.DateTime> _UpdatedAt;
		
		private EntitySet<Transaccion> _Transaccions;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnCodigoConvenioChanging(string value);
    partial void OnCodigoConvenioChanged();
    partial void OnEntidadNombreChanging(string value);
    partial void OnEntidadNombreChanged();
    partial void OnEntidadSiglaChanging(string value);
    partial void OnEntidadSiglaChanged();
    partial void OnEntidadNitChanging(string value);
    partial void OnEntidadNitChanged();
    partial void OnLlaveAChanging(string value);
    partial void OnLlaveAChanged();
    partial void OnLlaveBChanging(string value);
    partial void OnLlaveBChanged();
    partial void OnUriChanging(string value);
    partial void OnUriChanged();
    partial void OnActivoChanging(bool value);
    partial void OnActivoChanged();
    partial void OnCreatedAtChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedAtChanged();
    partial void OnUpdatedAtChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdatedAtChanged();
    #endregion
		
		public Convenio()
		{
			this._Transaccions = new EntitySet<Transaccion>(new Action<Transaccion>(this.attach_Transaccions), new Action<Transaccion>(this.detach_Transaccions));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id", Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="convenio", Storage="_CodigoConvenio", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string CodigoConvenio
		{
			get
			{
				return this._CodigoConvenio;
			}
			set
			{
				if ((this._CodigoConvenio != value))
				{
					this.OnCodigoConvenioChanging(value);
					this.SendPropertyChanging();
					this._CodigoConvenio = value;
					this.SendPropertyChanged("CodigoConvenio");
					this.OnCodigoConvenioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="entidad_nombre", Storage="_EntidadNombre", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string EntidadNombre
		{
			get
			{
				return this._EntidadNombre;
			}
			set
			{
				if ((this._EntidadNombre != value))
				{
					this.OnEntidadNombreChanging(value);
					this.SendPropertyChanging();
					this._EntidadNombre = value;
					this.SendPropertyChanged("EntidadNombre");
					this.OnEntidadNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="entidad_sigla", Storage="_EntidadSigla", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string EntidadSigla
		{
			get
			{
				return this._EntidadSigla;
			}
			set
			{
				if ((this._EntidadSigla != value))
				{
					this.OnEntidadSiglaChanging(value);
					this.SendPropertyChanging();
					this._EntidadSigla = value;
					this.SendPropertyChanged("EntidadSigla");
					this.OnEntidadSiglaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="entidad_nit", Storage="_EntidadNit", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string EntidadNit
		{
			get
			{
				return this._EntidadNit;
			}
			set
			{
				if ((this._EntidadNit != value))
				{
					this.OnEntidadNitChanging(value);
					this.SendPropertyChanging();
					this._EntidadNit = value;
					this.SendPropertyChanged("EntidadNit");
					this.OnEntidadNitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="llaveA", Storage="_LlaveA", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string LlaveA
		{
			get
			{
				return this._LlaveA;
			}
			set
			{
				if ((this._LlaveA != value))
				{
					this.OnLlaveAChanging(value);
					this.SendPropertyChanging();
					this._LlaveA = value;
					this.SendPropertyChanged("LlaveA");
					this.OnLlaveAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="llaveB", Storage="_LlaveB", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string LlaveB
		{
			get
			{
				return this._LlaveB;
			}
			set
			{
				if ((this._LlaveB != value))
				{
					this.OnLlaveBChanging(value);
					this.SendPropertyChanging();
					this._LlaveB = value;
					this.SendPropertyChanged("LlaveB");
					this.OnLlaveBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="uri", Storage="_Uri", DbType="NVarChar(1000) NOT NULL", CanBeNull=false)]
		public string Uri
		{
			get
			{
				return this._Uri;
			}
			set
			{
				if ((this._Uri != value))
				{
					this.OnUriChanging(value);
					this.SendPropertyChanging();
					this._Uri = value;
					this.SendPropertyChanged("Uri");
					this.OnUriChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="activo", Storage="_Activo", DbType="Bit NOT NULL")]
		public bool Activo
		{
			get
			{
				return this._Activo;
			}
			set
			{
				if ((this._Activo != value))
				{
					this.OnActivoChanging(value);
					this.SendPropertyChanging();
					this._Activo = value;
					this.SendPropertyChanged("Activo");
					this.OnActivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="created_at", Storage="_CreatedAt", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreatedAt
		{
			get
			{
				return this._CreatedAt;
			}
			set
			{
				if ((this._CreatedAt != value))
				{
					this.OnCreatedAtChanging(value);
					this.SendPropertyChanging();
					this._CreatedAt = value;
					this.SendPropertyChanged("CreatedAt");
					this.OnCreatedAtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="updated_at", Storage="_UpdatedAt", DbType="DateTime")]
		public System.Nullable<System.DateTime> UpdatedAt
		{
			get
			{
				return this._UpdatedAt;
			}
			set
			{
				if ((this._UpdatedAt != value))
				{
					this.OnUpdatedAtChanging(value);
					this.SendPropertyChanging();
					this._UpdatedAt = value;
					this.SendPropertyChanged("UpdatedAt");
					this.OnUpdatedAtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Convenio_Transaccion", Storage="_Transaccions", ThisKey="Id", OtherKey="ConvenioId")]
		public EntitySet<Transaccion> Transaccions
		{
			get
			{
				return this._Transaccions;
			}
			set
			{
				this._Transaccions.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Transaccions(Transaccion entity)
		{
			this.SendPropertyChanging();
			entity.Convenio = this;
		}
		
		private void detach_Transaccions(Transaccion entity)
		{
			this.SendPropertyChanging();
			entity.Convenio = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.transacciones")]
	public partial class Transaccion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _ConvenioId;
		
		private string _JsonEnvio;
		
		private string _JsonHash;
		
		private string _TipoTransaccion;
		
		private string _Estado;
		
		private System.Nullable<System.DateTime> _CreatedAt;
		
		private System.Nullable<System.DateTime> _UpdatedAt;
		
		private EntitySet<DatoTransaccion> _DatoTransaccions;
		
		private EntityRef<Convenio> _Convenio;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnConvenioIdChanging(int value);
    partial void OnConvenioIdChanged();
    partial void OnJsonEnvioChanging(string value);
    partial void OnJsonEnvioChanged();
    partial void OnJsonHashChanging(string value);
    partial void OnJsonHashChanged();
    partial void OnTipoTransaccionChanging(string value);
    partial void OnTipoTransaccionChanged();
    partial void OnEstadoChanging(string value);
    partial void OnEstadoChanged();
    partial void OnCreatedAtChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedAtChanged();
    partial void OnUpdatedAtChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdatedAtChanged();
    #endregion
		
		public Transaccion()
		{
			this._DatoTransaccions = new EntitySet<DatoTransaccion>(new Action<DatoTransaccion>(this.attach_DatoTransaccions), new Action<DatoTransaccion>(this.detach_DatoTransaccions));
			this._Convenio = default(EntityRef<Convenio>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id", Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="convenio_id", Storage="_ConvenioId", DbType="Int NOT NULL")]
		public int ConvenioId
		{
			get
			{
				return this._ConvenioId;
			}
			set
			{
				if ((this._ConvenioId != value))
				{
					this.OnConvenioIdChanging(value);
					this.SendPropertyChanging();
					this._ConvenioId = value;
					this.SendPropertyChanged("ConvenioId");
					this.OnConvenioIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="json_envio", Storage="_JsonEnvio", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string JsonEnvio
		{
			get
			{
				return this._JsonEnvio;
			}
			set
			{
				if ((this._JsonEnvio != value))
				{
					this.OnJsonEnvioChanging(value);
					this.SendPropertyChanging();
					this._JsonEnvio = value;
					this.SendPropertyChanged("JsonEnvio");
					this.OnJsonEnvioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="json_hash", Storage="_JsonHash", DbType="NVarChar(32)")]
		public string JsonHash
		{
			get
			{
				return this._JsonHash;
			}
			set
			{
				if ((this._JsonHash != value))
				{
					this.OnJsonHashChanging(value);
					this.SendPropertyChanging();
					this._JsonHash = value;
					this.SendPropertyChanged("JsonHash");
					this.OnJsonHashChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="tipo_transaccion", Storage="_TipoTransaccion", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TipoTransaccion
		{
			get
			{
				return this._TipoTransaccion;
			}
			set
			{
				if ((this._TipoTransaccion != value))
				{
					this.OnTipoTransaccionChanging(value);
					this.SendPropertyChanging();
					this._TipoTransaccion = value;
					this.SendPropertyChanged("TipoTransaccion");
					this.OnTipoTransaccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="estado", Storage="_Estado", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="created_at", Storage="_CreatedAt", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreatedAt
		{
			get
			{
				return this._CreatedAt;
			}
			set
			{
				if ((this._CreatedAt != value))
				{
					this.OnCreatedAtChanging(value);
					this.SendPropertyChanging();
					this._CreatedAt = value;
					this.SendPropertyChanged("CreatedAt");
					this.OnCreatedAtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="updated_at", Storage="_UpdatedAt", DbType="DateTime")]
		public System.Nullable<System.DateTime> UpdatedAt
		{
			get
			{
				return this._UpdatedAt;
			}
			set
			{
				if ((this._UpdatedAt != value))
				{
					this.OnUpdatedAtChanging(value);
					this.SendPropertyChanging();
					this._UpdatedAt = value;
					this.SendPropertyChanged("UpdatedAt");
					this.OnUpdatedAtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Transaccion_DatoTransaccion", Storage="_DatoTransaccions", ThisKey="Id", OtherKey="TransaccionId")]
		public EntitySet<DatoTransaccion> DatoTransaccions
		{
			get
			{
				return this._DatoTransaccions;
			}
			set
			{
				this._DatoTransaccions.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Convenio_Transaccion", Storage="_Convenio", ThisKey="ConvenioId", OtherKey="Id", IsForeignKey=true)]
		public Convenio Convenio
		{
			get
			{
				return this._Convenio.Entity;
			}
			set
			{
				Convenio previousValue = this._Convenio.Entity;
				if (((previousValue != value) 
							|| (this._Convenio.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Convenio.Entity = null;
						previousValue.Transaccions.Remove(this);
					}
					this._Convenio.Entity = value;
					if ((value != null))
					{
						value.Transaccions.Add(this);
						this._ConvenioId = value.Id;
					}
					else
					{
						this._ConvenioId = default(int);
					}
					this.SendPropertyChanged("Convenio");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DatoTransaccions(DatoTransaccion entity)
		{
			this.SendPropertyChanging();
			entity.Transaccion = this;
		}
		
		private void detach_DatoTransaccions(DatoTransaccion entity)
		{
			this.SendPropertyChanging();
			entity.Transaccion = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.datos_transaccion")]
	public partial class DatoTransaccion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _TransaccionId;
		
		private int _Anio;
		
		private int _Mes;
		
		private int _Dia;
		
		private int _NumeroSecuencia;
		
		private string _Numero;
		
		private string _XmlEnvio;
		
		private string _XmlEnvioEncriptado;
		
		private string _HashXml;
		
		private string _XmlRespuesta;
		
		private string _XmlRespuestaEncriptada;
		
		private System.Nullable<bool> _EsErroneo;
		
		private System.Nullable<System.DateTime> _CreatedAt;
		
		private System.Nullable<System.DateTime> _UpdatedAt;
		
		private EntityRef<Transaccion> _Transaccion;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnTransaccionIdChanging(int value);
    partial void OnTransaccionIdChanged();
    partial void OnAnioChanging(int value);
    partial void OnAnioChanged();
    partial void OnMesChanging(int value);
    partial void OnMesChanged();
    partial void OnDiaChanging(int value);
    partial void OnDiaChanged();
    partial void OnNumeroSecuenciaChanging(int value);
    partial void OnNumeroSecuenciaChanged();
    partial void OnNumeroChanging(string value);
    partial void OnNumeroChanged();
    partial void OnXmlEnvioChanging(string value);
    partial void OnXmlEnvioChanged();
    partial void OnXmlEnvioEncriptadoChanging(string value);
    partial void OnXmlEnvioEncriptadoChanged();
    partial void OnHashXmlChanging(string value);
    partial void OnHashXmlChanged();
    partial void OnXmlRespuestaChanging(string value);
    partial void OnXmlRespuestaChanged();
    partial void OnXmlRespuestaEncriptadaChanging(string value);
    partial void OnXmlRespuestaEncriptadaChanged();
    partial void OnEsErroneoChanging(System.Nullable<bool> value);
    partial void OnEsErroneoChanged();
    partial void OnCreatedAtChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedAtChanged();
    partial void OnUpdatedAtChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdatedAtChanged();
    #endregion
		
		public DatoTransaccion()
		{
			this._Transaccion = default(EntityRef<Transaccion>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id", Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="transaccion_id", Storage="_TransaccionId", DbType="Int NOT NULL")]
		public int TransaccionId
		{
			get
			{
				return this._TransaccionId;
			}
			set
			{
				if ((this._TransaccionId != value))
				{
					this.OnTransaccionIdChanging(value);
					this.SendPropertyChanging();
					this._TransaccionId = value;
					this.SendPropertyChanged("TransaccionId");
					this.OnTransaccionIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="anio", Storage="_Anio", DbType="Int NOT NULL")]
		public int Anio
		{
			get
			{
				return this._Anio;
			}
			set
			{
				if ((this._Anio != value))
				{
					this.OnAnioChanging(value);
					this.SendPropertyChanging();
					this._Anio = value;
					this.SendPropertyChanged("Anio");
					this.OnAnioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="mes", Storage="_Mes", DbType="Int NOT NULL")]
		public int Mes
		{
			get
			{
				return this._Mes;
			}
			set
			{
				if ((this._Mes != value))
				{
					this.OnMesChanging(value);
					this.SendPropertyChanging();
					this._Mes = value;
					this.SendPropertyChanged("Mes");
					this.OnMesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="dia", Storage="_Dia", DbType="Int NOT NULL")]
		public int Dia
		{
			get
			{
				return this._Dia;
			}
			set
			{
				if ((this._Dia != value))
				{
					this.OnDiaChanging(value);
					this.SendPropertyChanging();
					this._Dia = value;
					this.SendPropertyChanged("Dia");
					this.OnDiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="numero_secuencia", Storage="_NumeroSecuencia", DbType="Int NOT NULL")]
		public int NumeroSecuencia
		{
			get
			{
				return this._NumeroSecuencia;
			}
			set
			{
				if ((this._NumeroSecuencia != value))
				{
					this.OnNumeroSecuenciaChanging(value);
					this.SendPropertyChanging();
					this._NumeroSecuencia = value;
					this.SendPropertyChanged("NumeroSecuencia");
					this.OnNumeroSecuenciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="numero", Storage="_Numero", AutoSync=AutoSync.Always, DbType="VarChar(22) NOT NULL", CanBeNull=false, IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public string Numero
		{
			get
			{
				return this._Numero;
			}
			set
			{
				if ((this._Numero != value))
				{
					this.OnNumeroChanging(value);
					this.SendPropertyChanging();
					this._Numero = value;
					this.SendPropertyChanged("Numero");
					this.OnNumeroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="xml_envio", Storage="_XmlEnvio", DbType="NVarChar(3000)")]
		public string XmlEnvio
		{
			get
			{
				return this._XmlEnvio;
			}
			set
			{
				if ((this._XmlEnvio != value))
				{
					this.OnXmlEnvioChanging(value);
					this.SendPropertyChanging();
					this._XmlEnvio = value;
					this.SendPropertyChanged("XmlEnvio");
					this.OnXmlEnvioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="xml_envio_encriptado", Storage="_XmlEnvioEncriptado", DbType="NVarChar(3000)")]
		public string XmlEnvioEncriptado
		{
			get
			{
				return this._XmlEnvioEncriptado;
			}
			set
			{
				if ((this._XmlEnvioEncriptado != value))
				{
					this.OnXmlEnvioEncriptadoChanging(value);
					this.SendPropertyChanging();
					this._XmlEnvioEncriptado = value;
					this.SendPropertyChanged("XmlEnvioEncriptado");
					this.OnXmlEnvioEncriptadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="hashXml", Storage="_HashXml", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string HashXml
		{
			get
			{
				return this._HashXml;
			}
			set
			{
				if ((this._HashXml != value))
				{
					this.OnHashXmlChanging(value);
					this.SendPropertyChanging();
					this._HashXml = value;
					this.SendPropertyChanged("HashXml");
					this.OnHashXmlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="xml_respuesta", Storage="_XmlRespuesta", DbType="NVarChar(3000)")]
		public string XmlRespuesta
		{
			get
			{
				return this._XmlRespuesta;
			}
			set
			{
				if ((this._XmlRespuesta != value))
				{
					this.OnXmlRespuestaChanging(value);
					this.SendPropertyChanging();
					this._XmlRespuesta = value;
					this.SendPropertyChanged("XmlRespuesta");
					this.OnXmlRespuestaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="xml_respuesta_encriptada", Storage="_XmlRespuestaEncriptada", DbType="NVarChar(3000)")]
		public string XmlRespuestaEncriptada
		{
			get
			{
				return this._XmlRespuestaEncriptada;
			}
			set
			{
				if ((this._XmlRespuestaEncriptada != value))
				{
					this.OnXmlRespuestaEncriptadaChanging(value);
					this.SendPropertyChanging();
					this._XmlRespuestaEncriptada = value;
					this.SendPropertyChanged("XmlRespuestaEncriptada");
					this.OnXmlRespuestaEncriptadaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="es_erroneo", Storage="_EsErroneo", DbType="Bit")]
		public System.Nullable<bool> EsErroneo
		{
			get
			{
				return this._EsErroneo;
			}
			set
			{
				if ((this._EsErroneo != value))
				{
					this.OnEsErroneoChanging(value);
					this.SendPropertyChanging();
					this._EsErroneo = value;
					this.SendPropertyChanged("EsErroneo");
					this.OnEsErroneoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="created_at", Storage="_CreatedAt", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreatedAt
		{
			get
			{
				return this._CreatedAt;
			}
			set
			{
				if ((this._CreatedAt != value))
				{
					this.OnCreatedAtChanging(value);
					this.SendPropertyChanging();
					this._CreatedAt = value;
					this.SendPropertyChanged("CreatedAt");
					this.OnCreatedAtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="updated_at", Storage="_UpdatedAt", DbType="DateTime")]
		public System.Nullable<System.DateTime> UpdatedAt
		{
			get
			{
				return this._UpdatedAt;
			}
			set
			{
				if ((this._UpdatedAt != value))
				{
					this.OnUpdatedAtChanging(value);
					this.SendPropertyChanging();
					this._UpdatedAt = value;
					this.SendPropertyChanged("UpdatedAt");
					this.OnUpdatedAtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Transaccion_DatoTransaccion", Storage="_Transaccion", ThisKey="TransaccionId", OtherKey="Id", IsForeignKey=true)]
		public Transaccion Transaccion
		{
			get
			{
				return this._Transaccion.Entity;
			}
			set
			{
				Transaccion previousValue = this._Transaccion.Entity;
				if (((previousValue != value) 
							|| (this._Transaccion.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Transaccion.Entity = null;
						previousValue.DatoTransaccions.Remove(this);
					}
					this._Transaccion.Entity = value;
					if ((value != null))
					{
						value.DatoTransaccions.Add(this);
						this._TransaccionId = value.Id;
					}
					else
					{
						this._TransaccionId = default(int);
					}
					this.SendPropertyChanged("Transaccion");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
