//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Com.StartLineSoft.SincronizadorRedCoopcentral.WSRedCoopcentral {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSRedCoopcentral.IIncomingWebService")]
    public interface IIncomingWebService {
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:ECGTSIncomingSoapWebServiceIntf-IIncomingWebService) of message RequestRequest does not match the default value (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:ECGTSIncomingSoapWebServiceIntf-IIncomingWebService#Request", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        Com.StartLineSoft.SincronizadorRedCoopcentral.WSRedCoopcentral.RequestResponse Request(Com.StartLineSoft.SincronizadorRedCoopcentral.WSRedCoopcentral.RequestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ECGTSIncomingSoapWebServiceIntf-IIncomingWebService#Request", ReplyAction="*")]
        System.Threading.Tasks.Task<Com.StartLineSoft.SincronizadorRedCoopcentral.WSRedCoopcentral.RequestResponse> RequestAsync(Com.StartLineSoft.SincronizadorRedCoopcentral.WSRedCoopcentral.RequestRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:unECGIncomingSoapGlobal")]
    public partial class TECGIncomingRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string inputField;
        
        private string inputHashField;
        
        private string inputKeyField;
        
        private string inputKeyHashField;
        
        private string inputIdentifyField;
        
        private string inputIdentifyPinField;
        
        private string inputSecuenceField;
        
        /// <remarks/>
        public string Input {
            get {
                return this.inputField;
            }
            set {
                this.inputField = value;
                this.RaisePropertyChanged("Input");
            }
        }
        
        /// <remarks/>
        public string InputHash {
            get {
                return this.inputHashField;
            }
            set {
                this.inputHashField = value;
                this.RaisePropertyChanged("InputHash");
            }
        }
        
        /// <remarks/>
        public string InputKey {
            get {
                return this.inputKeyField;
            }
            set {
                this.inputKeyField = value;
                this.RaisePropertyChanged("InputKey");
            }
        }
        
        /// <remarks/>
        public string InputKeyHash {
            get {
                return this.inputKeyHashField;
            }
            set {
                this.inputKeyHashField = value;
                this.RaisePropertyChanged("InputKeyHash");
            }
        }
        
        /// <remarks/>
        public string InputIdentify {
            get {
                return this.inputIdentifyField;
            }
            set {
                this.inputIdentifyField = value;
                this.RaisePropertyChanged("InputIdentify");
            }
        }
        
        /// <remarks/>
        public string InputIdentifyPin {
            get {
                return this.inputIdentifyPinField;
            }
            set {
                this.inputIdentifyPinField = value;
                this.RaisePropertyChanged("InputIdentifyPin");
            }
        }
        
        /// <remarks/>
        public string InputSecuence {
            get {
                return this.inputSecuenceField;
            }
            set {
                this.inputSecuenceField = value;
                this.RaisePropertyChanged("InputSecuence");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:unECGIncomingSoapGlobal")]
    public partial class TECGIncomingResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int errorField;
        
        private string errorMsgField;
        
        private string outputField;
        
        private string outputHashField;
        
        private string outputKeyField;
        
        private string outputKeyHashField;
        
        private string outputSecuenceField;
        
        /// <remarks/>
        public int Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
                this.RaisePropertyChanged("Error");
            }
        }
        
        /// <remarks/>
        public string ErrorMsg {
            get {
                return this.errorMsgField;
            }
            set {
                this.errorMsgField = value;
                this.RaisePropertyChanged("ErrorMsg");
            }
        }
        
        /// <remarks/>
        public string Output {
            get {
                return this.outputField;
            }
            set {
                this.outputField = value;
                this.RaisePropertyChanged("Output");
            }
        }
        
        /// <remarks/>
        public string OutputHash {
            get {
                return this.outputHashField;
            }
            set {
                this.outputHashField = value;
                this.RaisePropertyChanged("OutputHash");
            }
        }
        
        /// <remarks/>
        public string OutputKey {
            get {
                return this.outputKeyField;
            }
            set {
                this.outputKeyField = value;
                this.RaisePropertyChanged("OutputKey");
            }
        }
        
        /// <remarks/>
        public string OutputKeyHash {
            get {
                return this.outputKeyHashField;
            }
            set {
                this.outputKeyHashField = value;
                this.RaisePropertyChanged("OutputKeyHash");
            }
        }
        
        /// <remarks/>
        public string OutputSecuence {
            get {
                return this.outputSecuenceField;
            }
            set {
                this.outputSecuenceField = value;
                this.RaisePropertyChanged("OutputSecuence");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Request", WrapperNamespace="urn:ECGTSIncomingSoapWebServiceIntf-IIncomingWebService", IsWrapped=true)]
    public partial class RequestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public Com.StartLineSoft.SincronizadorRedCoopcentral.WSRedCoopcentral.TECGIncomingRequest inp;
        
        public RequestRequest() {
        }
        
        public RequestRequest(Com.StartLineSoft.SincronizadorRedCoopcentral.WSRedCoopcentral.TECGIncomingRequest inp) {
            this.inp = inp;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RequestResponse", WrapperNamespace="urn:ECGTSIncomingSoapWebServiceIntf-IIncomingWebService", IsWrapped=true)]
    public partial class RequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public Com.StartLineSoft.SincronizadorRedCoopcentral.WSRedCoopcentral.TECGIncomingResponse @return;
        
        public RequestResponse() {
        }
        
        public RequestResponse(Com.StartLineSoft.SincronizadorRedCoopcentral.WSRedCoopcentral.TECGIncomingResponse @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IIncomingWebServiceChannel : Com.StartLineSoft.SincronizadorRedCoopcentral.WSRedCoopcentral.IIncomingWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IncomingWebServiceClient : System.ServiceModel.ClientBase<Com.StartLineSoft.SincronizadorRedCoopcentral.WSRedCoopcentral.IIncomingWebService>, Com.StartLineSoft.SincronizadorRedCoopcentral.WSRedCoopcentral.IIncomingWebService {
        
        public IncomingWebServiceClient() {
        }
        
        public IncomingWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IncomingWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IncomingWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IncomingWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Com.StartLineSoft.SincronizadorRedCoopcentral.WSRedCoopcentral.RequestResponse Com.StartLineSoft.SincronizadorRedCoopcentral.WSRedCoopcentral.IIncomingWebService.Request(Com.StartLineSoft.SincronizadorRedCoopcentral.WSRedCoopcentral.RequestRequest request) {
            return base.Channel.Request(request);
        }
        
        public Com.StartLineSoft.SincronizadorRedCoopcentral.WSRedCoopcentral.TECGIncomingResponse Request(Com.StartLineSoft.SincronizadorRedCoopcentral.WSRedCoopcentral.TECGIncomingRequest inp) {
            Com.StartLineSoft.SincronizadorRedCoopcentral.WSRedCoopcentral.RequestRequest inValue = new Com.StartLineSoft.SincronizadorRedCoopcentral.WSRedCoopcentral.RequestRequest();
            inValue.inp = inp;
            Com.StartLineSoft.SincronizadorRedCoopcentral.WSRedCoopcentral.RequestResponse retVal = ((Com.StartLineSoft.SincronizadorRedCoopcentral.WSRedCoopcentral.IIncomingWebService)(this)).Request(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Com.StartLineSoft.SincronizadorRedCoopcentral.WSRedCoopcentral.RequestResponse> Com.StartLineSoft.SincronizadorRedCoopcentral.WSRedCoopcentral.IIncomingWebService.RequestAsync(Com.StartLineSoft.SincronizadorRedCoopcentral.WSRedCoopcentral.RequestRequest request) {
            return base.Channel.RequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<Com.StartLineSoft.SincronizadorRedCoopcentral.WSRedCoopcentral.RequestResponse> RequestAsync(Com.StartLineSoft.SincronizadorRedCoopcentral.WSRedCoopcentral.TECGIncomingRequest inp) {
            Com.StartLineSoft.SincronizadorRedCoopcentral.WSRedCoopcentral.RequestRequest inValue = new Com.StartLineSoft.SincronizadorRedCoopcentral.WSRedCoopcentral.RequestRequest();
            inValue.inp = inp;
            return ((Com.StartLineSoft.SincronizadorRedCoopcentral.WSRedCoopcentral.IIncomingWebService)(this)).RequestAsync(inValue);
        }
    }
}
